name: Build Database

on:
  push:
    branches:
      - main
    paths-ignore:
      - release/autogen_database.json
      - release/autogen_database.json.gz
      - release/autogen_version.txt

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build database
        run: python tools/compiler/buildDatabase.py

      - name: Commit generated files
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
          else
            echo "No changes to commit."
          fi

      - name: Create pull request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update autogenerated database [skip ci]"
          branch: "bot/update-autogen-database"
          delete-branch: true
          title: "chore: update autogenerated database"
          body: "This PR was created automatically by GitHub Actions."
          add-paths: |
            packages/**/autogen_id
            release/autogen_database.json
            release/autogen_database.json.gz
            release/autogen_version.txt
